[package]
name = "liquidity_pool"
version = "0.1.0"
edition = "2021"
author =  ["Mikolaj Grzegorzek <mikolaj.grzegorzek@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
